version: "3.7"

services:
  app:
    image: app:0.0
    command: sh -c "/wait && npm run start"
    ports:
      - 3000:3000
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
      MYSQL_DB: User-Api
    depends_on:
      - mysql

  mysql:
    image: mysql:latest
    volumes:
      - todo-mysql-data:/var/lib/mysql
    environment: 
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: User-Api
    ports:
      - "3306:3306"
    expose:
      - 3306

volumes:
  todo-mysql-data:
